PortfolioBundle\Entity\Content:
    type: entity
    table: null
    repositoryClass: PortfolioBundle\Repository\ContentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
    lifecycleCallbacks: {  }
