# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: $2y$12$LqKt9OzZjSBt/KYNPn11KeEUuoRZ7ZSRWQuTAl.deXFZl2exLYFfK
                    admin:
                        password:  $2y$12$lqzlirPxxZ8N1uzgwMLCGeIcbu3DJS/Aw2DVn1LYWgz6iq3Tz2vcS
                        roles: 'ROLE_ADMIN'


    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: portfolio_login
                check_path: portfolio_login
                default_target_path: portfolio_admin
            logout:
                path: /logout
                target: portfolio_homepage
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }