portfolio_homepage:
    path:     /
    defaults: { _controller: PortfolioBundle:Default:index }

portfolio_projects:
    path: /projets
    defaults: { _controller: PortfolioBundle:Default:projects}

portfolio_about:
    path: /a-propos
    defaults: { _controller: PortfolioBundle:Default:about}

portfolio_contact:
    path: /contact
    defaults: { _controller: PortfolioBundle:Default:contact}

portfolio_picture:
        resource: "@PortfolioBundle/Resources/config/routing/picture.yml"
        prefix:   /picture

portfolio_content:
    resource: "@PortfolioBundle/Resources/config/routing/content.yml"
    prefix:   /content

